
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/componentes/AuthProvider";
import  Header  from "@/componentes/Header"
import 'tailwindcss/tailwind.css';


const poppins = Poppins({ 
  subsets:["latin"],
   weight:["400", "500","600","700"],
});

export const metadata  = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body 
        className={poppins.className}>
          <Header/>{children}</body>
      </AuthProvider>
    </html>
  );
}

